### PR TITLE
fix: colored text on windows

### LINKED ISSUE #1243: Colored text not working on Windows
Running the program on Windows produce an unexpected output with escaped [ANSI Escape Codes](http://en.wikipedia.org/wiki/ANSI_escape_code#Colors).

```powershell
PS C:\Users\foobar\Downloads> .\phoneinfoga.exe scan
←[37mRunning scan for phone number ...

←[0m←[31mgiven phone number is not valid←[0m
```

But the [color package](https://github.com/fatih/color) we use does support Windows so it should work fine. We should use `color.Output` explicitly everywhere, like above.

```go
// Windows supported too! Just don't forget to change the output to color.Output
fmt.Fprintf(color.Output, "Windows support: %s", color.GreenString("PASS"))
```

So we should replace each call to `fmt.Printf(...)` where it uses color, with `fmt.Fprintf(color.Output, ...)`. Also don't use os.Stdout directly but `color.Output`.

```diff
-err = output.GetOutput(output.Console, os.Stdout).Write(result, errs)
+err = output.GetOutput(output.Console, color.Output).Write(result, errs)
if err != nil {
```

### PR DESCRIPTION
**Pull request by vinicel**
Tested on the terminal powershell and cmd.

Resolves #1243

### CODE REVIEW

**Review by sundowndev — CHANGES_REQUESTED** [review]
Thanks for your PR @vinicel 🙏🏻 

This does work as intended. I realised the server's logs still produce unexpected output on Windows since the default writer for Gin is still stdout. Would you mind fixing that as well ? That should be done in [web/v2/api/server/server.go](https://github.com/sundowndev/phoneinfoga/blob/df5a97bb0828b0fb683a6b8c407645922cadbe00/web/v2/api/server/server.go#L14).

```diff
func NewServer() *Server {
+	gin.DefaultWriter = color.Output
	s := &Server{
-		router: gin.Default(),
+		router: gin.New(),
	}
+	s.router.Use(gin.Logger())
+	s.router.Use(gin.Recovery())
	s.registerRoutes()
	return s
}
```
That should do the trick. See [Gin docs](https://gin-gonic.com/zh-tw/docs/examples/using-middleware/).

Thanks!

File: cmd/root.go [hunk 1]
```diff
@@ -23,6 +23,6 @@ func Execute() {
 }
 
 func exitWithError(err error) {
-	fmt.Println(color.RedString(err.Error()))
+	fmt.Fprintf(color.Output, "%s\n", color.RedString(err.Error()))
```
Comment (sundowndev) [inline cmd/root.go:26]: After looking at the [docs](https://pkg.go.dev/github.com/fatih/color#Error), `color.Error` should be used here

**Review by sundowndev — APPROVED** [review]
